### ISSUE TITLE
Conflict with "Slackers' Delight (Postpone/Defer Button)" addon

### ISSUE THREAD

**Issue by Intergalacticmedic** [glutanimate/popup-dictionary#27]
#### Problem description

This addon doesn't work with the Slackers Delight addon. If it is disabled popup dictionary works just fine. Thank you for your work.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*
I use anki 2.1.15 

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=1

Add-ons:

AMBOSS add-on
TagSelectorV2
Postpone cards review
ImageResizer
Field History
Quick note and deck buttons Fork for 21
Tag Entry Enhancements
Answer Confirmation for 21
Image Occlusion Enhanced for Anki 21 alpha
Search and Replace Tags
Browser Resizer
Symbols
Night Mode
Pop-up Dictionary beta
Searching PDF reading  note-taking in Add dialog
Large and Colorful Buttons
Hierarchical Tags Addon 20  21
Zoom 21
remove linebreaks  do word wrap fork for 21
More Overview Stats
Maximum image height in card editor
Batch Editing
Mini Format Pack
ReMemorize Rescheduler with sibling and logging v121
Edit Field During Review Cloze
Frozen Fields
Removes Empty Note Types for 21
True Retention
More Overview Stats 21
right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable
Create Filtered Deck from the Browser
Web Browser - Search selection Import texts and images automatically
Enhance main window
Slackers Delight PostponeDefer Button
Review Heatmap
```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: macOS
- version: 10.13.6

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/59662273/72002880-bbab3e80-3261-11ea-9e96-a66b16a93ac3.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by lovac42** [comment]
I also received a bug report for this: https://github.com/lovac42/SlackersDelight/issues/4

How do you guys expect this addon to work? I've tested this with 2.1.15-21 and the dicts are popping up during review.

![image](https://user-images.githubusercontent.com/42665127/75316766-35a87e80-5834-11ea-8287-b0c0ddd9fec0.png)

![image](https://user-images.githubusercontent.com/42665127/75317016-e3b42880-5834-11ea-96d4-5a4a8b347001.png)

**Comment by glutanimate** [comment]
Thanks for chiming in @lovac42!

The expected behavior would be for the pop-ups to appear either on double-clicking a term or using Ctrl+Shift+D. I assume the latter might be the issue?

**Comment by lovac42** [comment]
With no other addons, only popupDict, Ctrl+Shift+D did not work either.
```JS error on line 208: Uncaught IndexSizeError: Failed to execute 'getRangeAt' on  'Selection': 0 is not a valid index.```

Tested on 15-21

**Comment by lovac42** [comment]
@Intergalacticmedic I reworked the code a little. The recent update should resolve this issue for mac users, try updating the addon by going to addon manager and click on the update button.

**Comment by Intergalacticmedic** [comment]
> @Intergalacticmedic I reworked the code a little. The recent update should resolve this issue for mac users, try updating the addon by going to addon manager and click on the update button.

It still doesn't work for me. Neither with double-click nor hotkeys.

**Comment by glutanimate** [comment]
@intergalacticmedic please disable all add-ons other than pop-up dictionary to confirm that this is not an issue with PD itself. Then please reenable all previously enabled add-ons aside from slackers delight to see whether this is a conflict with a different add-on. Some add-ons like earlier versions of Night Mode or the current version of Replay Buttons.

**Comment by Intergalacticmedic** [comment]
Popupdict works just fine when slackers delight addon is disabled. I have done all of that already. It is issue between these 2 addons for sure. Thank you.

**Comment by lovac42** [comment]
@Intergalacticmedic Just a note: On 2.1.15, disabled addons do not get updated. Make sure you disable the addon first, then updated both SD and PD to the latest versions. Or just to be sure, delete both addons first, then download the latest version available. I suspect this has more to do with old versions not updating correctly.

After you have done that, test out a simple card like cats or dogs first and see if that works.

And the last thing you can try is to rename the addon's respective folder name so that one loads first before the other. aSD, zPD or aPD, zSD.
